export interface MockLocation {
  id: string
  name: string
  type: "artist" | "shop"
  address: string
  city: string
  state: string
  zipCode: string
  coordinates: [number, number] // [longitude, latitude]
  rating: number
  reviewCount: number
  specialties: string[]
  priceRange: "low" | "medium" | "high"
  isOpen: boolean
  hours: {
    [key: string]: string
  }
  phone: string
  email: string
  website?: string
  instagram?: string
  images: string[]
  description: string
  artists?: string[] // For shops
}

export const mockLocations: MockLocation[] = [
  {
    id: "1",
    name: "Ink Masters Studio",
    type: "shop",
    address: "123 Mission Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94103",
    coordinates: [-122.4194, 37.7749],
    rating: 4.8,
    reviewCount: 127,
    specialties: ["Traditional", "Japanese", "Realism"],
    priceRange: "high",
    isOpen: true,
    hours: {
      monday: "10:00 AM - 8:00 PM",
      tuesday: "10:00 AM - 8:00 PM",
      wednesday: "10:00 AM - 8:00 PM",
      thursday: "10:00 AM - 8:00 PM",
      friday: "10:00 AM - 9:00 PM",
      saturday: "10:00 AM - 9:00 PM",
      sunday: "12:00 PM - 6:00 PM",
    },
    phone: "(415) 555-0123",
    email: "info@inkmasters.com",
    website: "https://inkmasters.com",
    instagram: "@inkmasterssf",
    images: ["/tattoo-shop-interior.png", "/placeholder.jpg"],
    description:
      "Premier tattoo studio in the heart of San Francisco, specializing in traditional and Japanese styles.",
    artists: ["Sarah Chen", "Mike Rodriguez", "Alex Thompson"],
  },
  {
    id: "2",
    name: "Sarah Chen",
    type: "artist",
    address: "123 Mission Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94103",
    coordinates: [-122.4194, 37.7749],
    rating: 4.9,
    reviewCount: 89,
    specialties: ["Fine Line", "Botanical", "Minimalist"],
    priceRange: "high",
    isOpen: true,
    hours: {
      monday: "Closed",
      tuesday: "11:00 AM - 7:00 PM",
      wednesday: "11:00 AM - 7:00 PM",
      thursday: "11:00 AM - 7:00 PM",
      friday: "11:00 AM - 8:00 PM",
      saturday: "10:00 AM - 8:00 PM",
      sunday: "Closed",
    },
    phone: "(415) 555-0124",
    email: "sarah@inkmasters.com",
    instagram: "@sarahchentattoo",
    images: ["/female-tattoo-artist-portrait-1.png", "/fine-line-tattoo-1.png"],
    description: "Specializing in delicate fine line work and botanical designs with over 8 years of experience.",
  },
  {
    id: "3",
    name: "Black Oak Tattoo",
    type: "shop",
    address: "456 Valencia Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94110",
    coordinates: [-122.4214, 37.7599],
    rating: 4.7,
    reviewCount: 203,
    specialties: ["Blackwork", "Geometric", "Traditional"],
    priceRange: "medium",
    isOpen: false,
    hours: {
      monday: "Closed",
      tuesday: "12:00 PM - 8:00 PM",
      wednesday: "12:00 PM - 8:00 PM",
      thursday: "12:00 PM - 8:00 PM",
      friday: "12:00 PM - 9:00 PM",
      saturday: "11:00 AM - 9:00 PM",
      sunday: "12:00 PM - 6:00 PM",
    },
    phone: "(415) 555-0125",
    email: "info@blackoaktattoo.com",
    website: "https://blackoaktattoo.com",
    instagram: "@blackoaksf",
    images: ["/black-oak-logo.png", "/dark-artistic-tattoo-studio.png"],
    description: "Bold blackwork and geometric designs in a welcoming, artistic environment.",
    artists: ["Marcus Johnson", "Luna Martinez", "David Kim"],
  },
  {
    id: "4",
    name: "Luna Martinez",
    type: "artist",
    address: "789 Sunset Boulevard",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90028",
    coordinates: [-118.2437, 34.0522],
    rating: 4.6,
    reviewCount: 156,
    specialties: ["Watercolor", "Abstract", "Floral"],
    priceRange: "medium",
    isOpen: true,
    hours: {
      monday: "Closed",
      tuesday: "Closed",
      wednesday: "1:00 PM - 8:00 PM",
      thursday: "1:00 PM - 8:00 PM",
      friday: "1:00 PM - 9:00 PM",
      saturday: "11:00 AM - 9:00 PM",
      sunday: "12:00 PM - 7:00 PM",
    },
    phone: "(323) 555-0126",
    email: "luna@example.com",
    instagram: "@lunamartineztattoo",
    images: ["/placeholder-user.jpg", "/botanical-tattoo-1.png"],
    description: "Creating vibrant watercolor tattoos that flow like painted art on skin.",
  },
  {
    id: "5",
    name: "Golden State Ink",
    type: "shop",
    address: "321 Hollywood Boulevard",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90028",
    coordinates: [-118.2437, 34.0522],
    rating: 4.5,
    reviewCount: 298,
    specialties: ["Realism", "Portraits", "Japanese"],
    priceRange: "high",
    isOpen: true,
    hours: {
      monday: "11:00 AM - 8:00 PM",
      tuesday: "11:00 AM - 8:00 PM",
      wednesday: "11:00 AM - 8:00 PM",
      thursday: "11:00 AM - 8:00 PM",
      friday: "11:00 AM - 9:00 PM",
      saturday: "10:00 AM - 9:00 PM",
      sunday: "12:00 PM - 7:00 PM",
    },
    phone: "(323) 555-0127",
    email: "info@goldenstateink.com",
    website: "https://goldenstateink.com",
    instagram: "@goldenstateink",
    images: ["/tattoo-shop-interior.png", "/japanese-dragon-tattoo.png"],
    description: "Los Angeles premier destination for photorealistic tattoos and Japanese traditional work.",
    artists: ["Carlos Rivera", "Emma Thompson", "Kenji Nakamura"],
  },
  {
    id: "6",
    name: "Carlos Rivera",
    type: "artist",
    address: "321 Hollywood Boulevard",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90028",
    coordinates: [-118.2437, 34.0522],
    rating: 4.8,
    reviewCount: 134,
    specialties: ["Realism", "Portraits", "Black & Gray"],
    priceRange: "high",
    isOpen: false,
    hours: {
      monday: "Closed",
      tuesday: "Closed",
      wednesday: "12:00 PM - 8:00 PM",
      thursday: "12:00 PM - 8:00 PM",
      friday: "12:00 PM - 9:00 PM",
      saturday: "11:00 AM - 9:00 PM",
      sunday: "1:00 PM - 7:00 PM",
    },
    phone: "(323) 555-0128",
    email: "carlos@goldenstateink.com",
    instagram: "@carlosriveratattoo",
    images: ["/placeholder-user.jpg", "/placeholder.jpg"],
    description: "Award-winning realism artist with 12+ years creating lifelike portraits and detailed artwork.",
  },
  {
    id: "7",
    name: "Electric Canvas",
    type: "shop",
    address: "654 Market Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94104",
    coordinates: [-122.4058, 37.7875],
    rating: 4.4,
    reviewCount: 87,
    specialties: ["Neo-Traditional", "Color Work", "Custom Designs"],
    priceRange: "medium",
    isOpen: true,
    hours: {
      monday: "Closed",
      tuesday: "12:00 PM - 8:00 PM",
      wednesday: "12:00 PM - 8:00 PM",
      thursday: "12:00 PM - 8:00 PM",
      friday: "12:00 PM - 9:00 PM",
      saturday: "11:00 AM - 9:00 PM",
      sunday: "1:00 PM - 6:00 PM",
    },
    phone: "(415) 555-0129",
    email: "info@electriccanvas.com",
    website: "https://electriccanvas.com",
    instagram: "@electriccanvassf",
    images: ["/placeholder.jpg", "/abstract-geometric-shapes.png"],
    description: "Modern tattoo studio focusing on vibrant neo-traditional and custom artistic designs.",
    artists: ["Riley Park", "Jordan Smith"],
  },
  {
    id: "8",
    name: "Jordan Smith",
    type: "artist",
    address: "987 Venice Beach",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90291",
    coordinates: [-118.4694, 33.985],
    rating: 4.7,
    reviewCount: 76,
    specialties: ["Geometric", "Dotwork", "Sacred Geometry"],
    priceRange: "medium",
    isOpen: true,
    hours: {
      monday: "Closed",
      tuesday: "Closed",
      wednesday: "2:00 PM - 9:00 PM",
      thursday: "2:00 PM - 9:00 PM",
      friday: "2:00 PM - 10:00 PM",
      saturday: "12:00 PM - 10:00 PM",
      sunday: "12:00 PM - 8:00 PM",
    },
    phone: "(310) 555-0130",
    email: "jordan@example.com",
    instagram: "@jordansmithgeometric",
    images: ["/placeholder-user.jpg", "/abstract-geometric-shapes.png"],
    description: "Precision geometric tattoos and sacred geometry designs with mathematical perfection.",
  },
]

export const getMapLocations = async (): Promise<MockLocation[]> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))
  return mockLocations
}

// Existing mock data exports
export const mockArtists = [
  {
    id: "1",
    name: "Sarah Chen",
    specialties: ["Fine Line", "Botanical", "Minimalist"],
    location: "San Francisco, CA",
    rating: 4.9,
    reviewCount: 127,
    image: "/female-tattoo-artist-portrait-1.png",
    portfolio: ["/fine-line-tattoo-1.png", "/botanical-tattoo-1.png"],
    priceRange: "$200-400/hour",
    availability: "Available",
    bio: "Specializing in delicate fine line work and botanical designs.",
    experience: "8 years",
    shop: "Ink Masters Studio",
  },
  {
    id: "2",
    name: "Marcus Johnson",
    specialties: ["Traditional", "Japanese", "Bold Lines"],
    location: "Los Angeles, CA",
    rating: 4.8,
    reviewCount: 203,
    image: "/placeholder-user.jpg",
    portfolio: ["/japanese-dragon-tattoo.png", "/placeholder.jpg"],
    priceRange: "$250-450/hour",
    availability: "Booked",
    bio: "Master of traditional American and Japanese tattoo styles.",
    experience: "12 years",
    shop: "Golden State Ink",
  },
  {
    id: "3",
    name: "Luna Martinez",
    specialties: ["Watercolor", "Abstract", "Floral"],
    location: "San Francisco, CA",
    rating: 4.7,
    reviewCount: 156,
    image: "/placeholder-user.jpg",
    portfolio: ["/botanical-tattoo-1.png", "/placeholder.jpg"],
    priceRange: "$180-350/hour",
    availability: "Available",
    bio: "Creating vibrant watercolor tattoos that flow like painted art.",
    experience: "6 years",
    shop: "Black Oak Tattoo",
  },
]

export const mockShops = [
  {
    id: "1",
    name: "Ink Masters Studio",
    location: "San Francisco, CA",
    rating: 4.8,
    reviewCount: 127,
    image: "/tattoo-shop-interior.png",
    specialties: ["Traditional", "Japanese", "Realism"],
    priceRange: "$200-500/hour",
    artists: ["Sarah Chen", "Mike Rodriguez", "Alex Thompson"],
    hours: "Mon-Sat: 10AM-8PM, Sun: 12PM-6PM",
    phone: "(415) 555-0123",
    address: "123 Mission Street, San Francisco, CA 94103",
  },
  {
    id: "2",
    name: "Black Oak Tattoo",
    location: "San Francisco, CA",
    rating: 4.7,
    reviewCount: 203,
    image: "/black-oak-logo.png",
    specialties: ["Blackwork", "Geometric", "Traditional"],
    priceRange: "$150-400/hour",
    artists: ["Marcus Johnson", "Luna Martinez", "David Kim"],
    hours: "Tue-Sat: 12PM-8PM, Sun: 12PM-6PM",
    phone: "(415) 555-0125",
    address: "456 Valencia Street, San Francisco, CA 94110",
  },
  {
    id: "3",
    name: "Golden State Ink",
    location: "Los Angeles, CA",
    rating: 4.9,
    reviewCount: 298,
    image: "/tattoo-shop-interior.png",
    specialties: ["Realism", "Portraits", "Japanese"],
    priceRange: "$250-600/hour",
    artists: ["Carlos Rivera", "Emma Thompson", "Kenji Nakamura"],
    hours: "Mon-Sat: 11AM-8PM, Sun: 12PM-7PM",
    phone: "(323) 555-0127",
    address: "321 Hollywood Boulevard, Los Angeles, CA 90028",
  },
]

export const tattooStyles = [
  {
    name: "Realism",
    description: "Photorealistic tattoos that capture incredible detail and lifelike imagery.",
    heroImage: "/styles/heroes/realism-hero.png",
    images: [
      "/styles/realism-portrait-1.png",
      "/styles/realism-animal-1.png",
      "/styles/realism-nature-1.png",
      "/styles/realism-portrait-2.png",
      "/styles/realism-flower-1.png",
      "/styles/realism-eye-1.png",
      "/styles/realism-landscape-1.png",
      "/styles/realism-animal-2.png",
      "/styles/realism-portrait-3.png",
    ],
    artists: mockArtists.filter((artist) => artist.specialties.includes("Realism")),
  },
  {
    name: "Traditional",
    description: "Classic American traditional tattoos with bold lines and vibrant colors.",
    heroImage: "/styles/heroes/traditional-hero.png",
    images: [
      "/styles/traditional-rose-1.png",
      "/styles/traditional-anchor-1.png",
      "/styles/traditional-eagle-1.png",
      "/styles/traditional-skull-1.png",
      "/styles/traditional-ship-1.png",
      "/styles/traditional-dagger-1.png",
      "/styles/traditional-heart-1.png",
      "/styles/traditional-swallow-1.png",
      "/styles/traditional-pin-up-1.png",
    ],
    artists: mockArtists.filter((artist) => artist.specialties.includes("Traditional")),
  },
  {
    name: "Japanese",
    description: "Traditional Japanese tattoo art featuring dragons, koi, and cherry blossoms.",
    heroImage: "/styles/heroes/japanese-hero.png",
    images: [
      "/styles/japanese-dragon-1.png",
      "/styles/japanese-koi-1.png",
      "/styles/japanese-cherry-1.png",
      "/styles/japanese-tiger-1.png",
      "/styles/japanese-phoenix-1.png",
      "/styles/japanese-wave-1.png",
      "/styles/japanese-oni-1.png",
      "/styles/japanese-samurai-1.png",
      "/styles/japanese-lotus-1.png",
    ],
    artists: mockArtists.filter((artist) => artist.specialties.includes("Japanese")),
  },
  {
    name: "Geometric",
    description: "Precise geometric patterns and sacred geometry designs.",
    heroImage: "/styles/heroes/geometric-hero.png",
    images: [
      "/styles/geometric-mandala-1.png",
      "/styles/geometric-animal-1.png",
      "/styles/geometric-sacred-1.png",
      "/styles/geometric-abstract-1.png",
      "/styles/geometric-flower-1.png",
      "/styles/geometric-triangle-1.png",
      "/styles/geometric-hexagon-1.png",
      "/styles/geometric-spiral-1.png",
      "/styles/geometric-crystal-1.png",
    ],
    artists: mockArtists.filter((artist) => artist.specialties.includes("Geometric")),
  },
  {
    name: "Watercolor",
    description: "Vibrant watercolor-style tattoos with flowing, painterly effects.",
    heroImage: "/styles/heroes/watercolor-hero.png",
    images: [
      "/styles/watercolor-flower-1.png",
      "/styles/watercolor-bird-1.png",
      "/styles/watercolor-abstract-1.png",
      "/styles/watercolor-butterfly-1.png",
      "/styles/watercolor-tree-1.png",
      "/styles/watercolor-splash-1.png",
      "/styles/watercolor-feather-1.png",
      "/styles/watercolor-galaxy-1.png",
      "/styles/watercolor-ocean-1.png",
    ],
    artists: mockArtists.filter((artist) => artist.specialties.includes("Watercolor")),
  },
  {
    name: "Blackwork",
    description: "Bold black ink designs ranging from tribal to modern abstract patterns.",
    heroImage: "/styles/heroes/blackwork-hero.png",
    images: [
      "/styles/blackwork-tribal-1.png",
      "/styles/blackwork-abstract-1.png",
      "/styles/blackwork-ornamental-1.png",
      "/styles/blackwork-botanical-1.png",
      "/styles/blackwork-geometric-1.png",
      "/styles/blackwork-mandala-1.png",
      "/styles/blackwork-animal-1.png",
      "/styles/blackwork-pattern-1.png",
      "/styles/blackwork-minimalist-1.png",
    ],
    artists: mockArtists.filter((artist) => artist.specialties.includes("Blackwork")),
  },
  {
    name: "Fine Line",
    description: "Delicate, precise line work creating minimalist and detailed designs.",
    heroImage: "/styles/heroes/fine-line-hero.png",
    images: [
      "/styles/fine-line-flower-1.png",
      "/styles/fine-line-minimalist-1.png",
      "/styles/fine-line-script-1.png",
      "/styles/fine-line-botanical-1.png",
      "/styles/fine-line-geometric-1.png",
      "/styles/fine-line-animal-1.png",
      "/styles/fine-line-constellation-1.png",
      "/styles/fine-line-portrait-1.png",
      "/styles/fine-line-abstract-1.png",
    ],
    artists: mockArtists.filter((artist) => artist.specialties.includes("Fine Line")),
  },
]
